LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE = libcliserv
LOCAL_SRC_FILES = cliserv.c
LOCAL_CFLAGS = -I$(LOCAL_PATH)/android
include $(BUILD_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE = nbd-client
LOCAL_SRC_FILES = nbd-client.c
LOCAL_CFLAGS = -I$(LOCAL_PATH)/android -DPROG_NAME=\"$(LOCAL_MODULE)\" -DPACKAGE_VERSION=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_STRING=\"\"
LOCAL_MODULE_PATH := $(TARGET_ROOT_OUT_SBIN)
LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_STATIC_LIBRARIES = libcliserv libm libc
include $(BUILD_EXECUTABLE)
